//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SBSWebProject.Web.NewApi.com.mellatinsurance.dev {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AgancyTravelInsSoap", Namespace="http://tempuri.org/")]
    public partial class AgancyTravelIns : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPriceInquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerInsuranceOperationCompleted;
        
        private System.Threading.SendOrPostCallback confirmInsuranceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCountriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getZoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelInsuranceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInsuranceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AgancyTravelIns() {
            this.Url = global::SBSWebProject.Web.NewApi.Properties.Settings.Default.SBSWebProject_Web_NewApi_com_mellatinsurance_dev_AgancyTravelIns;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPriceInquiryCompletedEventHandler GetPriceInquiryCompleted;
        
        /// <remarks/>
        public event registerInsuranceCompletedEventHandler registerInsuranceCompleted;
        
        /// <remarks/>
        public event confirmInsuranceCompletedEventHandler confirmInsuranceCompleted;
        
        /// <remarks/>
        public event getCountriesCompletedEventHandler getCountriesCompleted;
        
        /// <remarks/>
        public event getZoneCompletedEventHandler getZoneCompleted;
        
        /// <remarks/>
        public event cancelInsuranceCompletedEventHandler cancelInsuranceCompleted;
        
        /// <remarks/>
        public event getInsuranceCompletedEventHandler getInsuranceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPriceInquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TISPriceInfo GetPriceInquiry(UserInfo userInfo, long countryCode, string birthDate, int durationOfStay, long zoneCode, int companyCode) {
            object[] results = this.Invoke("GetPriceInquiry", new object[] {
                        userInfo,
                        countryCode,
                        birthDate,
                        durationOfStay,
                        zoneCode,
                        companyCode});
            return ((TISPriceInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetPriceInquiryAsync(UserInfo userInfo, long countryCode, string birthDate, int durationOfStay, long zoneCode, int companyCode) {
            this.GetPriceInquiryAsync(userInfo, countryCode, birthDate, durationOfStay, zoneCode, companyCode, null);
        }
        
        /// <remarks/>
        public void GetPriceInquiryAsync(UserInfo userInfo, long countryCode, string birthDate, int durationOfStay, long zoneCode, int companyCode, object userState) {
            if ((this.GetPriceInquiryOperationCompleted == null)) {
                this.GetPriceInquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriceInquiryOperationCompleted);
            }
            this.InvokeAsync("GetPriceInquiry", new object[] {
                        userInfo,
                        countryCode,
                        birthDate,
                        durationOfStay,
                        zoneCode,
                        companyCode}, this.GetPriceInquiryOperationCompleted, userState);
        }
        
        private void OnGetPriceInquiryOperationCompleted(object arg) {
            if ((this.GetPriceInquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPriceInquiryCompleted(this, new GetPriceInquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registerInsurance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TISInsuranceInfo registerInsurance(UserInfo UserInfo, TISInsuranceInsertData insuranceData, int CompanyCode) {
            object[] results = this.Invoke("registerInsurance", new object[] {
                        UserInfo,
                        insuranceData,
                        CompanyCode});
            return ((TISInsuranceInfo)(results[0]));
        }
        
        /// <remarks/>
        public void registerInsuranceAsync(UserInfo UserInfo, TISInsuranceInsertData insuranceData, int CompanyCode) {
            this.registerInsuranceAsync(UserInfo, insuranceData, CompanyCode, null);
        }
        
        /// <remarks/>
        public void registerInsuranceAsync(UserInfo UserInfo, TISInsuranceInsertData insuranceData, int CompanyCode, object userState) {
            if ((this.registerInsuranceOperationCompleted == null)) {
                this.registerInsuranceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterInsuranceOperationCompleted);
            }
            this.InvokeAsync("registerInsurance", new object[] {
                        UserInfo,
                        insuranceData,
                        CompanyCode}, this.registerInsuranceOperationCompleted, userState);
        }
        
        private void OnregisterInsuranceOperationCompleted(object arg) {
            if ((this.registerInsuranceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerInsuranceCompleted(this, new registerInsuranceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/confirmInsurance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TISInsuranceInfo confirmInsurance(UserInfo userInfo, long serialNo) {
            object[] results = this.Invoke("confirmInsurance", new object[] {
                        userInfo,
                        serialNo});
            return ((TISInsuranceInfo)(results[0]));
        }
        
        /// <remarks/>
        public void confirmInsuranceAsync(UserInfo userInfo, long serialNo) {
            this.confirmInsuranceAsync(userInfo, serialNo, null);
        }
        
        /// <remarks/>
        public void confirmInsuranceAsync(UserInfo userInfo, long serialNo, object userState) {
            if ((this.confirmInsuranceOperationCompleted == null)) {
                this.confirmInsuranceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmInsuranceOperationCompleted);
            }
            this.InvokeAsync("confirmInsurance", new object[] {
                        userInfo,
                        serialNo}, this.confirmInsuranceOperationCompleted, userState);
        }
        
        private void OnconfirmInsuranceOperationCompleted(object arg) {
            if ((this.confirmInsuranceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmInsuranceCompleted(this, new confirmInsuranceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCountries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TISCountryInfo[] getCountries(UserInfo userinfo) {
            object[] results = this.Invoke("getCountries", new object[] {
                        userinfo});
            return ((TISCountryInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void getCountriesAsync(UserInfo userinfo) {
            this.getCountriesAsync(userinfo, null);
        }
        
        /// <remarks/>
        public void getCountriesAsync(UserInfo userinfo, object userState) {
            if ((this.getCountriesOperationCompleted == null)) {
                this.getCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCountriesOperationCompleted);
            }
            this.InvokeAsync("getCountries", new object[] {
                        userinfo}, this.getCountriesOperationCompleted, userState);
        }
        
        private void OngetCountriesOperationCompleted(object arg) {
            if ((this.getCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCountriesCompleted(this, new getCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getZone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TISZoneInfo[] getZone(UserInfo userinfo) {
            object[] results = this.Invoke("getZone", new object[] {
                        userinfo});
            return ((TISZoneInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void getZoneAsync(UserInfo userinfo) {
            this.getZoneAsync(userinfo, null);
        }
        
        /// <remarks/>
        public void getZoneAsync(UserInfo userinfo, object userState) {
            if ((this.getZoneOperationCompleted == null)) {
                this.getZoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZoneOperationCompleted);
            }
            this.InvokeAsync("getZone", new object[] {
                        userinfo}, this.getZoneOperationCompleted, userState);
        }
        
        private void OngetZoneOperationCompleted(object arg) {
            if ((this.getZoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getZoneCompleted(this, new getZoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancelInsurance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TISInsuranceInfo cancelInsurance(UserInfo userinfo, string PolicyNo) {
            object[] results = this.Invoke("cancelInsurance", new object[] {
                        userinfo,
                        PolicyNo});
            return ((TISInsuranceInfo)(results[0]));
        }
        
        /// <remarks/>
        public void cancelInsuranceAsync(UserInfo userinfo, string PolicyNo) {
            this.cancelInsuranceAsync(userinfo, PolicyNo, null);
        }
        
        /// <remarks/>
        public void cancelInsuranceAsync(UserInfo userinfo, string PolicyNo, object userState) {
            if ((this.cancelInsuranceOperationCompleted == null)) {
                this.cancelInsuranceOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelInsuranceOperationCompleted);
            }
            this.InvokeAsync("cancelInsurance", new object[] {
                        userinfo,
                        PolicyNo}, this.cancelInsuranceOperationCompleted, userState);
        }
        
        private void OncancelInsuranceOperationCompleted(object arg) {
            if ((this.cancelInsuranceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelInsuranceCompleted(this, new cancelInsuranceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInsurance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TISInsuranceInfo getInsurance(UserInfo userinfo, string PolicyNo) {
            object[] results = this.Invoke("getInsurance", new object[] {
                        userinfo,
                        PolicyNo});
            return ((TISInsuranceInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getInsuranceAsync(UserInfo userinfo, string PolicyNo) {
            this.getInsuranceAsync(userinfo, PolicyNo, null);
        }
        
        /// <remarks/>
        public void getInsuranceAsync(UserInfo userinfo, string PolicyNo, object userState) {
            if ((this.getInsuranceOperationCompleted == null)) {
                this.getInsuranceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInsuranceOperationCompleted);
            }
            this.InvokeAsync("getInsurance", new object[] {
                        userinfo,
                        PolicyNo}, this.getInsuranceOperationCompleted, userState);
        }
        
        private void OngetInsuranceOperationCompleted(object arg) {
            if ((this.getInsuranceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInsuranceCompleted(this, new getInsuranceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo {
        
        private string userNameField;
        
        private string passWordField;
        
        private string nationalCodeField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        public string NationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TISZoneInfo {
        
        private long zoneCodeField;
        
        private string zoneTitleField;
        
        private string zoneTitleEnglishField;
        
        private int errorCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        public long zoneCode {
            get {
                return this.zoneCodeField;
            }
            set {
                this.zoneCodeField = value;
            }
        }
        
        /// <remarks/>
        public string zoneTitle {
            get {
                return this.zoneTitleField;
            }
            set {
                this.zoneTitleField = value;
            }
        }
        
        /// <remarks/>
        public string zoneTitleEnglish {
            get {
                return this.zoneTitleEnglishField;
            }
            set {
                this.zoneTitleEnglishField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TISCustomerInfo {
        
        private long codeField;
        
        private string nationalCodeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string latinFirstNameField;
        
        private string latinLastNameField;
        
        private string birthDateField;
        
        private string mobileField;
        
        private string emailField;
        
        private bool isMaleField;
        
        private string birthplaceField;
        
        private string birthDate_PassPortField;
        
        /// <remarks/>
        public long Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string nationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string latinFirstName {
            get {
                return this.latinFirstNameField;
            }
            set {
                this.latinFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string latinLastName {
            get {
                return this.latinLastNameField;
            }
            set {
                this.latinLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public bool isMale {
            get {
                return this.isMaleField;
            }
            set {
                this.isMaleField = value;
            }
        }
        
        /// <remarks/>
        public string Birthplace {
            get {
                return this.birthplaceField;
            }
            set {
                this.birthplaceField = value;
            }
        }
        
        /// <remarks/>
        public string BirthDate_PassPort {
            get {
                return this.birthDate_PassPortField;
            }
            set {
                this.birthDate_PassPortField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TISCountryInfo {
        
        private long codeField;
        
        private string titleField;
        
        private long zoneCodeField;
        
        private string zoneTitleField;
        
        private string zoneTitleEnglishField;
        
        private int errorCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        public long Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public long zoneCode {
            get {
                return this.zoneCodeField;
            }
            set {
                this.zoneCodeField = value;
            }
        }
        
        /// <remarks/>
        public string zoneTitle {
            get {
                return this.zoneTitleField;
            }
            set {
                this.zoneTitleField = value;
            }
        }
        
        /// <remarks/>
        public string zoneTitleEnglish {
            get {
                return this.zoneTitleEnglishField;
            }
            set {
                this.zoneTitleEnglishField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TISInsuranceInfo {
        
        private long bimehNoField;
        
        private string policyNoField;
        
        private string passportNoField;
        
        private int durationOfStayField;
        
        private int statusField;
        
        private string attpolicyNoField;
        
        private System.DateTime cancelDateField;
        
        private TISCountryInfo countryField;
        
        private TISCustomerInfo customerField;
        
        private TISPriceInfo priceField;
        
        private int errorCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        public long bimehNo {
            get {
                return this.bimehNoField;
            }
            set {
                this.bimehNoField = value;
            }
        }
        
        /// <remarks/>
        public string policyNo {
            get {
                return this.policyNoField;
            }
            set {
                this.policyNoField = value;
            }
        }
        
        /// <remarks/>
        public string passportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
            }
        }
        
        /// <remarks/>
        public int durationOfStay {
            get {
                return this.durationOfStayField;
            }
            set {
                this.durationOfStayField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string AttpolicyNo {
            get {
                return this.attpolicyNoField;
            }
            set {
                this.attpolicyNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cancelDate {
            get {
                return this.cancelDateField;
            }
            set {
                this.cancelDateField = value;
            }
        }
        
        /// <remarks/>
        public TISCountryInfo country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public TISCustomerInfo customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public TISPriceInfo price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TISPriceInfo {
        
        private int countryCodeField;
        
        private decimal priceGrossField;
        
        private decimal priceAvarezField;
        
        private decimal priceTaxField;
        
        private decimal priceDiscountField;
        
        private decimal priceTotalField;
        
        private int errorCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        public int countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal priceGross {
            get {
                return this.priceGrossField;
            }
            set {
                this.priceGrossField = value;
            }
        }
        
        /// <remarks/>
        public decimal priceAvarez {
            get {
                return this.priceAvarezField;
            }
            set {
                this.priceAvarezField = value;
            }
        }
        
        /// <remarks/>
        public decimal PriceTax {
            get {
                return this.priceTaxField;
            }
            set {
                this.priceTaxField = value;
            }
        }
        
        /// <remarks/>
        public decimal PriceDiscount {
            get {
                return this.priceDiscountField;
            }
            set {
                this.priceDiscountField = value;
            }
        }
        
        /// <remarks/>
        public decimal PriceTotal {
            get {
                return this.priceTotalField;
            }
            set {
                this.priceTotalField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TISInsuranceInsertData {
        
        private string nationalCodeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string latinFirstNameField;
        
        private string latinLastNameField;
        
        private string birthDateField;
        
        private string mobileField;
        
        private string emailField;
        
        private int genderField;
        
        private string birthplaceField;
        
        private string passportNoField;
        
        private long countryCodeField;
        
        private int durationOfStayField;
        
        private long zoneCodeField;
        
        private string birthDate_PassPortField;
        
        /// <remarks/>
        public string nationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string latinFirstName {
            get {
                return this.latinFirstNameField;
            }
            set {
                this.latinFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string latinLastName {
            get {
                return this.latinLastNameField;
            }
            set {
                this.latinLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Birthplace {
            get {
                return this.birthplaceField;
            }
            set {
                this.birthplaceField = value;
            }
        }
        
        /// <remarks/>
        public string passportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
            }
        }
        
        /// <remarks/>
        public long countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public int durationOfStay {
            get {
                return this.durationOfStayField;
            }
            set {
                this.durationOfStayField = value;
            }
        }
        
        /// <remarks/>
        public long ZoneCode {
            get {
                return this.zoneCodeField;
            }
            set {
                this.zoneCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BirthDate_PassPort {
            get {
                return this.birthDate_PassPortField;
            }
            set {
                this.birthDate_PassPortField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetPriceInquiryCompletedEventHandler(object sender, GetPriceInquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPriceInquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPriceInquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TISPriceInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TISPriceInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void registerInsuranceCompletedEventHandler(object sender, registerInsuranceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registerInsuranceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registerInsuranceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TISInsuranceInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TISInsuranceInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void confirmInsuranceCompletedEventHandler(object sender, confirmInsuranceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmInsuranceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmInsuranceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TISInsuranceInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TISInsuranceInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getCountriesCompletedEventHandler(object sender, getCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TISCountryInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TISCountryInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getZoneCompletedEventHandler(object sender, getZoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getZoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getZoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TISZoneInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TISZoneInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void cancelInsuranceCompletedEventHandler(object sender, cancelInsuranceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelInsuranceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelInsuranceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TISInsuranceInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TISInsuranceInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getInsuranceCompletedEventHandler(object sender, getInsuranceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInsuranceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInsuranceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TISInsuranceInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TISInsuranceInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591